export const fantasticQuestions = [
  { block: "F - Familia y Amigos", field: "fantastic_1", label: "¿Tengo una relación cercana y de confianza con mis padres o cuidadores?", reversed: false },
  { block: "F - Familia y Amigos", field: "fantastic_2", label: "¿Cuento con amigos o compañeros de equipo con quienes hablar de mis problemas?", reversed: false },
  { block: "F - Familia y Amigos", field: "fantastic_3", label: "¿Me siento querido y valorado en mi entorno familiar?", reversed: false },
  { block: "F - Familia y Amigos", field: "fantastic_4", label: "¿Recibo apoyo de mi familia para asistir a mis entrenamientos de fútbol?", reversed: false },
  { block: "F - Familia y Amigos", field: "fantastic_5", label: "¿Soy capaz de dar y recibir afecto de manera natural?", reversed: false },
  { block: "A - Actividad Física", field: "fantastic_6", label: "¿Realizo actividad física intensa (entrenamientos) más de 3 veces por semana?", reversed: false },
  { block: "A - Actividad Física", field: "fantastic_7", label: "¿Me mantengo activo durante el día (camino, subo escaleras, juego en el parque)?", reversed: false },
  { block: "A - Actividad Física", field: "fantastic_8", label: "¿Realizo ejercicios de estiramiento o movilidad antes y después de jugar?", reversed: false },
  { block: "A - Actividad Física", field: "fantastic_9", label: "¿Participo con entusiasmo en las actividades grupales de la fundación?", reversed: false },
  { block: "A - Actividad Física", field: "fantastic_10", label: "¿Prefiero las actividades al aire libre sobre los videojuegos o estar sentado?", reversed: false },
  { block: "N - Nutrición", field: "fantastic_11", label: "¿Desayuno todos los días antes de ir a estudiar o entrenar?", reversed: false },
  { block: "N - Nutrición", field: "fantastic_12", label: "¿Consumo al menos 2 porciones de fruta y 3 de verduras al día?", reversed: false },
  { block: "N - Nutrición", field: "fantastic_13", label: "¿Bebo suficiente agua durante el día (más de 1.5 litros)?", reversed: false },
  { block: "N - Nutrición", field: "fantastic_14", label: "¿Evito el consumo de bebidas azucaradas (gaseosas, jugos artificiales)?", reversed: false },
  { block: "N - Nutrición", field: "fantastic_15", label: "¿Evito comer comida chatarra o fritos más de 2 veces por semana?", reversed: false },
  { block: "T - Tabaco y Tóxicos", field: "fantastic_16", label: "¿Evito fumar cigarrillos o usar vapeadores?", reversed: false },
  { block: "T - Tabaco y Tóxicos", field: "fantastic_17", label: "¿Me alejo de lugares donde la gente está fumando?", reversed: false },
  { block: "T - Tabaco y Tóxicos", field: "fantastic_18", label: "¿Soy consciente de que el tabaco daña mis pulmones para el fútbol?", reversed: false },
  { block: "T - Tabaco y Tóxicos", field: "fantastic_19", label: "¿Evito el consumo de sustancias psicoactivas (drogas)?", reversed: false },
  { block: "T - Tabaco y Tóxicos", field: "fantastic_20", label: "¿Mis amigos cercanos son personas que no consumen sustancias tóxicas?", reversed: false },
  { block: "A - Alcohol", field: "fantastic_21", label: "¿Me mantengo alejado del consumo de alcohol?", reversed: false },
  { block: "A - Alcohol", field: "fantastic_22", label: "¿Entiendo que el alcohol afecta mi crecimiento y recuperación muscular?", reversed: false },
  { block: "A - Alcohol", field: "fantastic_23", label: "¿Evito asistir a reuniones donde el centro sea el consumo de alcohol?", reversed: false },
  { block: "A - Alcohol", field: "fantastic_24", label: '¿Me siento capaz de decir "no" si alguien me ofrece una bebida alcohólica?', reversed: false },
  { block: "A - Alcohol", field: "fantastic_25", label: "¿Conozco los riesgos de las bebidas embriagantes para mi salud?", reversed: false },
  { block: "S - Sueño y Estrés", field: "fantastic_26", label: "¿Duermo entre 8 y 10 horas seguidas cada noche?", reversed: false },
  { block: "S - Sueño y Estrés", field: "fantastic_27", label: "¿Me despierto sintiéndome descansado y con energía para entrenar?", reversed: false },
  { block: "S - Sueño y Estrés", field: "fantastic_28", label: "¿Soy capaz de relajarme después de un día de mucho estudio o ejercicio?", reversed: false },
  { block: "S - Sueño y Estrés", field: "fantastic_29", label: "¿Hablo con alguien cuando me siento bajo mucha presión?", reversed: false },
  { block: "S - Sueño y Estrés", field: "fantastic_30", label: "¿Evito usar pantallas (celular/TV) una hora antes de ir a dormir?", reversed: false },
  { block: "T - Trabajo (Estudio) y Tipo de Personalidad", field: "fantastic_31", label: "¿Me siento satisfecho con mi desempeño escolar o académico?", reversed: false },
  { block: "T - Trabajo (Estudio) y Tipo de Personalidad", field: "fantastic_32", label: "¿Puedo controlar mi enojo cuando pierdo un partido o cometo un error?", reversed: false },
  { block: "T - Trabajo (Estudio) y Tipo de Personalidad", field: "fantastic_33", label: "¿Soy paciente conmigo mismo cuando algo no me sale bien en la cancha?", reversed: false },
  { block: "T - Trabajo (Estudio) y Tipo de Personalidad", field: "fantastic_34", label: "¿Suelo cumplir con mis tareas y deberes a tiempo sin estresarme?", reversed: false },
  { block: "T - Trabajo (Estudio) y Tipo de Personalidad", field: "fantastic_35", label: "¿Me considero una persona competitiva de forma sana (sin agresividad)?", reversed: false },
  { block: "I - Introspección (Imagen Interior)", field: "fantastic_36", label: "¿Me siento una persona valiosa y con buenas capacidades?", reversed: false },
  { block: "I - Introspección (Imagen Interior)", field: "fantastic_37", label: "¿Soy optimista sobre mi futuro en el deporte y en mi vida?", reversed: false },
  { block: "I - Introspección (Imagen Interior)", field: "fantastic_38", label: "¿Me siento feliz la mayor parte del tiempo?", reversed: false },
  { block: "I - Introspección (Imagen Interior)", field: "fantastic_39", label: "¿Soy consciente de mis fortalezas y de lo que debo mejorar?", reversed: false },
  { block: "I - Introspección (Imagen Interior)", field: "fantastic_40", label: "¿Me trato a mí mismo con respeto y cuidado?", reversed: false },
  { block: "C - Conducción y Comportamiento Social", field: "fantastic_41", label: "¿Uso siempre los implementos de seguridad (espinilleras, calzado adecuado)?", reversed: false },
  { block: "C - Conducción y Comportamiento Social", field: "fantastic_42", label: "¿Respeto las normas de tránsito al caminar o andar en bicicleta hacia el club?", reversed: false },
  { block: "C - Conducción y Comportamiento Social", field: "fantastic_43", label: "¿Sigo las normas de convivencia y respeto a mis entrenadores?", reversed: false },
  { block: "C - Conducción y Comportamiento Social", field: "fantastic_44", label: "¿Respeto a mis rivales y árbitros durante los partidos?", reversed: false },
  { block: "C - Conducción y Comportamiento Social", field: "fantastic_45", label: "¿Busco ayuda profesional o de un adulto cuando me siento enfermo o lesionado?", reversed: false },
];
